server:
  port: 9090

spring:
  main:
      web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: cliente-service
            uri: http://cliente-service:9091
            predicates:
            - Path=/clientes/**

          - id: compra-service
            uri: http://compra-service:9092
            predicates:
            - Path=/compras/**
          
          - id: producto-service
            uri: http://producto-service:9093
            predicates:
            - Path=/productos/**
          
          - id: venta-service
            uri: http://venta-service:9094
            predicates:
            - Path=/ventas/**

          - id: envio-service
            uri: http://envio-service:9095
            predicates:
            - Path=/envios/**  

          - id: inventario-service
            uri: http://inventario-service:9096
            predicates:
            - Path=/inventarios/** 

          - id: resena-service
            uri: http://resena-service:9097
            predicates:
            - Path=/resenas/** 

          - id: notificacion-service
            uri: http://notificacion-service:9098
            predicates:
            - Path=/notificaciones/**

          - id: soporte-service
            uri: http://soporte-service:9099
            predicates:
            - Path=/soportes/**