spring.application.name=envio-service
server.port=9095

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/bd_envio?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

logging.file.name=logs/envio-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n

api.base-url=http://localhost:9090
api.compra.exists=/compras/%d/exists